version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: pdfsiegel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pdfsiegel
      MYSQL_USER: pdfuser
      MYSQL_PASSWORD: pdfpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - pdfsiegel_network

  # PHP Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pdfsiegel_backend
    ports:
      - "8888:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/uploads:/var/www/html/uploads
    depends_on:
      - mysql
    networks:
      - pdfsiegel_network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=pdfsiegel
      - DB_USER=pdfuser
      - DB_PASS=pdfpass

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pdfsiegel_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - pdfsiegel_network
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8888

volumes:
  mysql_data:

networks:
  pdfsiegel_network:
    driver: bridge
